spring:
    datasource:
        url: jdbc:h2:C:\Users\logonrmlocal\Documents\Git\library-batch\library-batch;DB_CLOSE_ON_EXIT=FALSE
        username: fiap
        password: fiap
file:
    path: C:\Users\logonrmlocal\Documents\Git\library-batch\medeleta.txt